### ISSUE TITLE
PROXY TEST ALWAYS FAILS

### ISSUE THREAD

**Issue by snipers-lab** [lnxcz/nitro-generator#1]
can you help me with continue to checker without checking for proxies?

**Comment by lnxcz** [comment]
you can disable proxy checker, but you must have some proxies in proxies.txt

**Comment by snipers-lab** [comment]
i did it but it shows invalid proxies and removed all proxies...i also use auto -scrap option same happens

**Comment by lnxcz** [comment]
Theres problem with the proxy scrape website. I will try to fix it.

**Comment by snipers-lab** [comment]
thank you

**Comment by Stodius** [comment]
This is also happening to me. Will it be fixed soon?

**Comment by snipers-lab** [comment]
idk

**Comment by snipers-lab** [comment]
**Leave** _something_ [`me`](

- 

@ #1. url

)
