### ISSUE TITLE
Need help on installing "py -3 -m pip install -r requirements.txt"

### ISSUE THREAD

**Issue by SniperXKiller** [lnxcz/nitro-generator#15]
How do you install "py -3 -m pip install -r requirements.txt"?

**Comment by AntsyBoi** [comment]
Do you have python installed?

**Comment by SniperXKiller** [comment]
I have python 3.8 installed

**Comment by AntsyBoi** [comment]
Are you actively inside the correct folder?

**Comment by SniperXKiller** [comment]
I think so

**Comment by AntsyBoi** [comment]
> I think so

Make sure you are then try it, make sure you're also in the generator folder.

**Comment by SniperXKiller** [comment]
ok I found the problem

**Comment by SniperXKiller** [comment]
fixed it

**Comment by DirtyGaming** [comment]
How did you fix it?

**Comment by AnonymousCube** [comment]
I installed Python 3.9 and I place it out of zipper folder (all file) trying launching the file but the app closed by it self after launched.
