### ISSUE TITLE
ssl.SSLError: [SSL] unknown error (_ssl.c:852)

### ISSUE THREAD

**Issue by redpenguinyt** [lnxcz/nitro-generator#26]
Here is the full error:
`$~/Downloads/nitro-generator-master/generator$ python3 main.py 
sh: 1: cls: not found
[ § ] Discord Nitro Generator made by LnX | Licensed under MIT License
[ § ] You can follow me on Github: https://github.com/lnxcz

[ > ] How much codes will be generated: 100

[ ? ] Classic Nitro is 16chars and Boost Nitro is 24chars
[ > ] Boost codes or Classic codes (boost or classic): classic
[ > ] Enable Checker (yes or no): yes
[ > ] Auto proxy scrape (yes or no): yes

[ ? ] If no, every check will be on random proxy.
[ > ] Multiple checks for proxy (yes or no): no
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 340, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] unknown error (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 47, in <module>
    scrape()
  File "main.py", line 30, in scrape
    r = requests.get('https://api.proxyscrape.com/?request=displayproxies&proxytype=http&timeout=1500&ssl=yes')
  File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:852)'),))
`
I installed both libraries

**Comment by HxmzaTareen** [comment]
did you find a fix to this?

**Comment by ledges** [comment]
> Here is the full error: `$~/Downloads/nitro-generator-master/generator$ python3 main.py sh: 1: cls: not found [ § ] Discord Nitro Generator made by LnX | Licensed under MIT License [ § ] You can follow me on Github: https://github.com/lnxcz
> 
> [ > ] How much codes will be generated: 100
> 
> [ ? ] Classic Nitro is 16chars and Boost Nitro is 24chars [ > ] Boost codes or Classic codes (boost or classic): classic [ > ] Enable Checker (yes or no): yes [ > ] Auto proxy scrape (yes or no): yes
> 
> [ ? ] If no, every check will be on random proxy. [ > ] Multiple checks for proxy (yes or no): no Traceback (most recent call last): File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen chunked=chunked) File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request self._validate_conn(conn) File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn conn.connect() File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 340, in connect ssl_context=context) File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket return context.wrap_socket(sock, server_hostname=server_hostname) File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket _context=self, _session=session) File "/usr/lib/python3.6/ssl.py", line 817, in **init** self.do_handshake() File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake self._sslobj.do_handshake() File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL] unknown error (_ssl.c:852)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send timeout=timeout File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen _stacktrace=sys.exc_info()[2]) File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment raise MaxRetryError(_pool, url, error or ResponseError(cause)) urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:852)'),))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "main.py", line 47, in scrape() File "main.py", line 30, in scrape r = requests.get('https://api.proxyscrape.com/?request=displayproxies&proxytype=http&timeout=1500&ssl=yes') File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get return request('get', url, params=params, **kwargs) File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in request resp = self.send(prep, **send_kwargs) File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/sessions.py", line 655, in send r = adapter.send(request, **kwargs) File "/home/redpenguin/.local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send raise SSLError(e, request=request) requests.exceptions.SSLError: HTTPSConnectionPool(host='api.proxyscrape.com', port=443): Max retries exceeded with url: /?request=displayproxies&proxytype=http&timeout=1500&ssl=yes (Caused by SSLError(SSLError(1, '[SSL] unknown error (_ssl.c:852)'),)) ` I installed both libraries

ratelimits.
