### ISSUE TITLE
sussy

### ISSUE THREAD

**Issue by Robatortas** [lnxcz/nitro-generator#5]
Sussy

**Comment by Robatortas** [comment]
and i dont know if this is supposed to happen but it says... 

 If no, every check will be on random proxy.
[ > ] Multiple checks for proxy (yes or no):

**Comment by Robatortas** [comment]
![Captura de pantalla (168)](https://user-images.githubusercontent.com/72624799/95618790-7ef3ba00-0a22-11eb-9107-bd76014e070b.png)

**Comment by lnxcz** [comment]
That's beacuse you used proxy scraper, which is not that good. To make it work fast and properly you must find or buy some good HTTPS proxies

**Comment by Robatortas** [comment]
thanks, it didnt work for me, but thank you!!

**Comment by luissilva1044894** [comment]
Throws a `list index out of range`, when `proxies.txt` is empty https://github.com/lnxcz/nitro-generator/blob/4251c5e2f4b998b6b7fa72d9d373c948dee3357c/main.py#L91 

Throws a `Not supported proxy scheme` (proxies=proxies) https://github.com/lnxcz/nitro-generator/blob/4251c5e2f4b998b6b7fa72d9d373c948dee3357c/main.py#L110

**Comment by CTRL-ALT-EXIST** [comment]
@luissilva1044894 Make a separate issue. I will be working on it in the meantime :)

**Comment by luissilva1044894** [comment]
@CTRL-ALT-EXIST Well... I just reported cuz there are some exceptions being handled by those try/catch, and isn't directly related to `using proxy scraper`.

I'm not using this project and I don't want to.

**Comment by CTRL-ALT-EXIST** [comment]
@Robatortas if this issue is solved please close it
